### ISSUE TITLE
Parallel search not working

### ISSUE THREAD

**Issue by ddurai** [seqan/seqan3#1962]
## Platform

  - SeqAn version: seqAn3
  - Operating system: Linux ddurai 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

  - Compiler:7.5.0

## Question

Dear SeqAn developers

I am trying to develop a correction algorithm for which I am using seqAn3. As the part of the algorithm, I have to search a string in an index. i am trying to parallelize my search using the following search config:

```cpp
#include <seqan3/core/algorithm/configuration.hpp>
#include <seqan3/search/configuration/max_error.hpp>
#include <seqan3/search/configuration/parallel.hpp>

seqan3::configuration const cfg = seqan3::search_cfg::max_error_total{seqan3::search_cfg::error_count{2}} |
                                  seqan3::search_cfg::max_error_substitution{seqan3::search_cfg::error_count{2}} |
                                  seqan3::search_cfg::parallel{8};
```

However, i encounter the following error:

```
/path_to_seqan/seqan3/include/seqan3/search/configuration/parallel.hpp:33:79: error: ‘search_config_id’ is not a member of ‘seqan3::search_cfg::detail’
 using parallel = seqan3::detail::parallel_mode<std::integral_constant<detail::search_config_id,

/path_to_seqan/seqan3/include/seqan3/search/configuration/parallel.hpp:34:79: error: ‘search_config_id’ is not a member of ‘seqan3::search_cfg::detail’
                                                                       detail::search_config_id::parallel>>;
```
Can you please help me with the issue

regards
Dilip

**Comment by eseiler** [comment]
Hello Dilip,

the snippet you posted compiles with GCC 7.5.0 on the current master branch.
What version of SeqAn3 are you using?

**Comment by ddurai** [comment]
Hi eseiler,
I am using seqan3 version 3.0.1 downloaded from github

**Comment by eseiler** [comment]
Thanks!

If you're using 3.0.1, the correct syntax would be
```cpp
#include <seqan3/core/algorithm/configuration.hpp>
#include <seqan3/search/configuration/max_error.hpp>
#include <seqan3/search/configuration/parallel.hpp>

seqan3::configuration const cfg = seqan3::search_cfg::max_error{seqan3::search_cfg::total{2},
                                                                seqan3::search_cfg::substitution{2}} |
                                  seqan3::search_cfg::parallel{8};
```

On the current master, it is
```cpp
#include <seqan3/core/algorithm/configuration.hpp>
#include <seqan3/search/configuration/max_error.hpp>
#include <seqan3/search/configuration/parallel.hpp>

seqan3::configuration const cfg = seqan3::search_cfg::max_error_total{seqan3::search_cfg::error_count{2}} |
                                  seqan3::search_cfg::max_error_substitution{seqan3::search_cfg::error_count{2}} |
                                  seqan3::search_cfg::parallel{8};
```

I tried both, and they should work.

**However**, the more important thing is that in 3.0.1 there is a `parallel` config element, but no actual implementation for the parallel search; i.e. the `parallel` configuration has no effect.

We implemented this feature since then, so I would recommend switching to the current master to be able to use the parallel search.

**Comment by ddurai** [comment]
Hi eseiler,

Thanks for your reply. I updaed the version of SeqAn3 from the current master. However, I now encounter a new error:

In file included from /home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/source/BarcodeCorrection.cpp:17:0:
/home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/seqan3/include/seqan3/search/search.hpp: In instantiation of ‘seqan3::search(queries_t&&, const index_t&, const configuration_t&)::<lambda()> [with index_t = seqan3::fm_index<char, (seqan3::text_layout)1, sdsl::csa_wt<sdsl::wt_pc<sdsl::balanced_shape, sdsl::int_vector<1>, sdsl::rank_support_v<1, 1>, sdsl::select_support_scan<>, sdsl::select_support_scan<0>, sdsl::byte_tree<> >, 16, 10000000, sdsl::sa_order_sa_sampling<>, sdsl::isa_sampling<>, sdsl::plain_byte_alphabet> >; queries_t = ranges::single_view<std::__cxx11::basic_string<char> >; configuration_t = seqan3::configuration<seqan3::detail::parallel_mode<std::integral_constant<seqan3::detail::search_config_id, (seqan3::detail::search_config_id)9> >, seqan3::search_cfg::max_error_total, seqan3::search_cfg::max_error_substitution>]’:
/home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/seqan3/include/seqan3/search/search.hpp:135:66:   required from ‘struct seqan3::search(queries_t&&, const index_t&, const configuration_t&) [with index_t = seqan3::fm_index<char, (seqan3::text_layout)1, sdsl::csa_wt<sdsl::wt_pc<sdsl::balanced_shape, sdsl::int_vector<1>, sdsl::rank_support_v<1, 1>, sdsl::select_support_scan<>, sdsl::select_support_scan<0>, sdsl::byte_tree<> >, 16, 10000000, sdsl::sa_order_sa_sampling<>, sdsl::isa_sampling<>, sdsl::plain_byte_alphabet> >; queries_t = ranges::single_view<std::__cxx11::basic_string<char> >; configuration_t = seqan3::configuration<seqan3::detail::parallel_mode<std::integral_constant<seqan3::detail::search_config_id, (seqan3::detail::search_config_id)9> >, seqan3::search_cfg::max_error_total, seqan3::search_cfg::max_error_substitution>]::<lambda()>’
/home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/seqan3/include/seqan3/search/search.hpp:132:10:   required from ‘auto seqan3::search(queries_t&&, const index_t&, const configuration_t&) [with index_t = seqan3::fm_index<char, (seqan3::text_layout)1, sdsl::csa_wt<sdsl::wt_pc<sdsl::balanced_shape, sdsl::int_vector<1>, sdsl::rank_support_v<1, 1>, sdsl::select_support_scan<>, sdsl::select_support_scan<0>, sdsl::byte_tree<> >, 16, 10000000, sdsl::sa_order_sa_sampling<>, sdsl::isa_sampling<>, sdsl::plain_byte_alphabet> >; queries_t = ranges::single_view<std::__cxx11::basic_string<char> >; configuration_t = seqan3::configuration<seqan3::detail::parallel_mode<std::integral_constant<seqan3::detail::search_config_id, (seqan3::detail::search_config_id)9> >, seqan3::search_cfg::max_error_total, seqan3::search_cfg::max_error_substitution>]’
/home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/seqan3/include/seqan3/search/search.hpp:156:18:   required from ‘auto seqan3::search(query_t, const index_t&, const configuration_t&) [with index_t = seqan3::fm_index<char, (seqan3::text_layout)1, sdsl::csa_wt<sdsl::wt_pc<sdsl::balanced_shape, sdsl::int_vector<1>, sdsl::rank_support_v<1, 1>, sdsl::select_support_scan<>, sdsl::select_support_scan<0>, sdsl::byte_tree<> >, 16, 10000000, sdsl::sa_order_sa_sampling<>, sdsl::isa_sampling<>, sdsl::plain_byte_alphabet> >; query_t = std::__cxx11::basic_string<char>; configuration_t = seqan3::configuration<seqan3::detail::parallel_mode<std::integral_constant<seqan3::detail::search_config_id, (seqan3::detail::search_config_id)9> >, seqan3::search_cfg::max_error_total, seqan3::search_cfg::max_error_substitution>]’
/home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/source/BarcodeCorrection.cpp:74:53:   required from here
/home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/seqan3/include/seqan3/search/search.hpp:135:83: error: ‘class seqan3::detail::parallel_mode<std::integral_constant<seqan3::detail::search_config_id, (seqan3::detail::search_config_id)9> >’ has no member named ‘value’
             return execution_handler_t{get<search_cfg::parallel>(complete_config).value};
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/seqan3/include/seqan3/search/search.hpp:135:88: error: no matching function for call to ‘seqan3::detail::execution_handler_parallel::execution_handler_parallel(<brace-enclosed initializer list>)’
             return execution_handler_t{get<search_cfg::parallel>(complete_config).value};
                                                                                        ^
In file included from /home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/seqan3/include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp:20:0,
                 from /home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/seqan3/include/seqan3/search/search.hpp:19,
                 from /home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/source/BarcodeCorrection.cpp:17:
/home/dilip/Work/Codes/SingleCellAnalysisTutorial/SingleCellTCRAnalysisVersion1/seqan3/include/seqan3/core/algorithm/detail/execution_handler_parallel.hpp:94:5: note: candidate: seqan3::detail::execution_handler_parallel::execution_handler_parallel(seqan3::detail::execution_handler_parallel&&)

Can you help me ith the error message

**Comment by eseiler** [comment]
This is indeed a bug and needs to be fixed.

Thanks for spotting and sorry for the inconvenience; I'll provide a patch shortly.

**Comment by ddurai** [comment]
Thanks for dealing with the error :). looking forward to the updated version

**Comment by eseiler** [comment]
The issue is fixed and parallel search works as intended now :)

Feel free to reopen the issue, if you still have questions regarding this; 
or open a new issue if you encounter other difficulties.

**Comment by ddurai** [comment]
Thanks a lot for solving the bug. it works now :)
