### ISSUE TITLE
gcc-7.2.0 Compiler error 

### ISSUE THREAD

**Issue by JensUweUlrich** [seqan/seqan3#1202]
## Platform

  - SeqAn version: 3.0.0
  - Operating system:  Debian GNU/Linux 9.9
  - Compiler: GCC-7.2.0

## Description

When I try to compile my application with cmake & make I get an error from the compiler. This error does not occur on a system with GCC-7.4.0

### How to repeat the problem

Just try to compile a tool that uses the argument parser

### Expected behaviour

Compilation should succeed without errors.

### Actual behaviour

The following error message occurs:

In file included from /mnt/biolibs/conda/ulrichj/.conda/envs/readuntil/gcc/include/c++/bits/basic_string.h:48:0,
                 from /mnt/biolibs/conda/ulrichj/.conda/envs/readuntil/gcc/include/c++/string:52,
                 from /home/ulrichj/tools/ReadUntil/src/main/mhc.cpp:1:
/home/ulrichj/tools/seqan3/include/seqan3/argument_parser/detail/version_check.hpp:409:58:   in constexpr expansion of  std::basic_string_view<char>(((const char*)"UNREGISTERED_APP"))’
/mnt/biolibs/conda/ulrichj/.conda/envs/readuntil/gcc/include/c++/string_view:100:58: error: call to non-constexpr function ‘static std::size_t std::char_traits<char>::length(const char_type*)’
       : _M_len{__str == nullptr ? 0 : traits_type::length(__str)},
                                       ~~~~~~~~~~~~~~~~~~~^~~~~~~
/home/ulrichj/tools/seqan3/include/seqan3/argument_parser/detail/version_check.hpp:415:9:   in constexpr expansion of ‘std::basic_string_view<char>(((const char*)"[SEQAN3 INFO] :: A new SeqAn3 version is available online.\012[SEQAN3 INFO] :: Please visit www.github.com/seqan/seqan3.git for an update\012[SEQAN3 INFO] :: or inform the developer of this app.\012[SEQAN3 INFO] :: If you don\'t wish to receive further notifications, set --version-check OFF.\012\012"))’
/mnt/biolibs/conda/ulrichj/.conda/envs/readuntil/gcc/include/c++/string_view:100:58: error: call to non-constexpr function ‘static std::size_t std::char_traits<char>::length(const char_type*)’
/home/ulrichj/tools/seqan3/include/seqan3/argument_parser/detail/version_check.hpp:421:9:   in constexpr expansion of ‘std::basic_string_view<char>(((const char*)"[SEQAN3 INFO] :: Thank you for using SeqAn!\012[SEQAN3 INFO] :: Do you wish to register your app for update notifications?\012[SEQAN3 INFO] :: Just send an email to support@seqan.de with your app name and version number.\012[SEQAN3 INFO] :: If you don\'t wish to receive further notifications, set --version-check OFF.\012\012"))’
/mnt/biolibs/conda/ulrichj/.conda/envs/readuntil/gcc/include/c++/string_view:100:58: error: call to non-constexpr function ‘static std::size_t std::char_traits<char>::length(const char_type*)’
/home/ulrichj/tools/seqan3/include/seqan3/argument_parser/detail/version_check.hpp:425:9:   in constexpr expansion of ‘std::basic_string_view<char>(((const char*)"[APP INFO] :: We noticed the app version you use is newer than the one registered with us.\012[APP INFO] :: Please send us an email with the new version so we can correct it (support@seqan.de)\012\012"))’
/mnt/biolibs/conda/ulrichj/.conda/envs/readuntil/gcc/include/c++/string_view:100:58: error: call to non-constexpr function ‘static std::size_t std::char_traits<char>::length(const char_type*)’
main/CMakeFiles/ReadUntil.dir/build.make:62: recipe for target 'main/CMakeFiles/ReadUntil.dir/mhc.cpp.o' failed
make[2]: *** [main/CMakeFiles/ReadUntil.dir/mhc.cpp.o] Error 1
CMakeFiles/Makefile2:201: recipe for target 'main/CMakeFiles/ReadUntil.dir/all' failed
make[1]: *** [main/CMakeFiles/ReadUntil.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by h-2** [comment]
Yes, it's a bug in gcc-7.2. We only support the most recent minor release of the each compiler, but this shouldn't be a problem, because every platform that receives gcc-7.x will receive gcc-7.(x+1).

**Comment by h-2** [comment]
See also http://docs.seqan.de/seqan/3-master-user/about_api.html

**Comment by JensUweUlrich** [comment]
Thanks for the quick reply. I suspected this to be a bug in the compiler. Unfortunately the latest version released under Conda is 7.2. And that means Seqan3 is currently not usable for me on our servers at the RKI.

**Comment by h-2** [comment]
According to #1121 conda has 7.3 which seems to work.

In any case I would strongly suggest filing a bug report with conda. Although they don't look that way, the "minor releases" of GCC are actually patch-level releases. Not getting patches seems like a real infrastructure problem.

If we needed to support every patch-level release, it would increase the compiler-matrix by a  factor of 10 right now and that's not even considering compilers like clang that we will support in the future. Also I am not aware of any packaging system that systematically makes outdated patch releases available so I don't even now how to do this even if we wanted to.

**Comment by JensUweUlrich** [comment]
I completely unterstand your point. It's definitely not feasible for you to support every compiler version. I have to figure out how I could get the latest gcc7 version installed on our servers.

BTW: When trying to compile with gcc-7.3.0, I get the following error message:

In file included from /home/ulrichj/tools/seqan3/include/seqan3/io/sequence_file/input.hpp:34:0,
                 from /home/ulrichj/tools/ReadUntil/src/main/mhc.cpp:21:
/home/ulrichj/tools/seqan3/include/seqan3/io/detail/misc_input.hpp: In function 'std::unique_ptr<std::basic_istream<char_t>, std::function<void(std::basic_istream<char_t>*)> > seqan3::detail::make_secondary_istream(std::basic_istream<char_t>&, std::experimental::filesystem::v1::__cxx11::path&)':
/home/ulrichj/tools/seqan3/include/seqan3/io/detail/misc_input.hpp:105:46: error: 'contrib' has not been declared
     if (read_chars == magic_number.size() && contrib::_bgzfCheckHeader(magic_number.data())) // BGZF
                                              ^~~~~~~
main/CMakeFiles/ReadUntil.dir/build.make:62: recipe for target 'main/CMakeFiles/ReadUntil.dir/mhc.cpp.o' failed

**Comment by h-2** [comment]
We have had other reports that GCC-7.3.0 works, but I can't double check that right now. Like I said, I would recommend creating a bug-report with Conda that the package needs updating.

I am not completely sure how Conda works, but a quick glance at the web-site shows that there are more recent packages also:
  * https://anaconda.org/anaconda/gxx_linux-64 (8.2.0)
  * https://anaconda.org/nwani/gxx_impl_linux-64 (9.1.0)

Do none of these work? What's the process for updating packages in Conda? Are patch level releases not included automatically?

**Comment by smehringer** [comment]
Hi @JensUweUlrich 

> BTW: When trying to compile with gcc-7.3.0, I get the following error message:
In file included from /home/ulrichj/tools/seqan3/include/seqan3/io/sequence_file/input.hpp:34:0,
from /home/ulrichj/tools/ReadUntil/src/main/mhc.cpp:21:
...

This is a bug I already reported (#1106) because file IO cannot be included if the zlib is not present. We will try to fix this soon!

Thanks for reporting anyway :)

PS: Tiny style polish: It is very helpful for readability if you wrap the error messages in code blocks with three back ticks ``... 
e.g. you error message would be
```
In file included from /home/ulrichj/tools/seqan3/include/seqan3/io/sequence_file/input.hpp:34:0,
from /home/ulrichj/tools/ReadUntil/src/main/mhc.cpp:21:
/home/ulrichj/tools/seqan3/include/seqan3/io/detail/misc_input.hpp: In function 'std::unique_ptr<std::basic_istream<char_t>, std::function<void(std::basic_istream<char_t>*)> > seqan3::detail::make_secondary_istream(std::basic_istream<char_t>&, std::experimental::filesystem::v1::__cxx11::path&)':
/home/ulrichj/tools/seqan3/include/seqan3/io/detail/misc_input.hpp:105:46: error: 'contrib' has not been declared
if (read_chars == magic_number.size() && contrib::_bgzfCheckHeader(magic_number.data())) // BGZF
^~~~~~~
main/CMakeFiles/ReadUntil.dir/build.make:62: recipe for target 'main/CMakeFiles/ReadUntil.dir/mhc.cpp.o' failed
```

**Comment by smehringer** [comment]
Hi @JensUweUlrich

we fixed the issue with the zlib, so if you use the most recent version of gcc7 you should be fine.

Feel free to reopen the issue if you encounter any more problems.

**Comment by JensUweUlrich** [comment]
Thanks a lot! Now it works fine with gcc-7.3.0.

Best wishes
Jens
